[package]
name = "lala"
version = "0.1.0"
edition = "2021"

[workspace]
menbers = ["lab"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.7.1"
